spring:
  jpa:
    database: default
    generate-ddl: true
    open-in-view: false
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: validate
    properties:
      hibernate.cache.use_second_level_cache: false
      #hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.default_schema: public
      hibernate.format_sql: true
    show-sql: ${SHOW_SQL:false}
  datasource:
    hikari:
      maximum-pool-size: 15
      connection-timeout: 10000
      initialization-fail-timeout: 60000
    initialization-mode: always
#   data: classpath:/1-data-postgres.sql
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USER:db-user}
    password: ${DATABASE_PASSWORD:delirium}
